import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import { FaBus, FaMapMarkerAlt, FaMoneyBillWave, FaClock, FaRoute, FaSearch } from "react-icons/fa";
import FAQ from "../components/sections/FAQ";

const features = [
  { icon: FaRoute, title: "Find the right route", text: "Search your starting point and destination to see available public vehicles." },
  { icon: FaMapMarkerAlt, title: "Board with confidence", text: "Get useful route and stop information before you leave the house." },
  { icon: FaMoneyBillWave, title: "Know the fare", text: "Compare standard and student fares for your journey." },
];

function Home() {
  const navigate = useNavigate();
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  function handleSearch(event) {
    event.preventDefault();
    if (from.trim() && to.trim()) navigate(`/routes?from=${encodeURIComponent(from.trim())}&to=${encodeURIComponent(to.trim())}`);
  }

  return <div className="bg-paper text-ink-900">
    <div className="border-b border-marigold-100 bg-marigold-50 px-4 py-2 text-center text-xs font-semibold text-marigold-700">🚌 Commuter tip: carry your student ID to claim your fare discount.</div>
    <header className="relative overflow-hidden bg-ink-950">
      <div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="hero-grid" />
      <div className="relative mx-auto max-w-6xl px-4 pb-20 pt-16 text-center sm:px-6 sm:pb-28 sm:pt-24">
        <span className="inline-flex items-center gap-2 rounded-full border border-marigold-500/30 bg-marigold-500/15 px-3 py-1 text-xs font-bold text-marigold-400"><FaMapMarkerAlt /> Made for Kathmandu Valley commuters</span>
        <h1 className="mx-auto mt-6 max-w-4xl font-display text-4xl font-semibold leading-tight text-paper-100 sm:text-5xl lg:text-6xl">Never guess your <span className="text-marigold-400">local bus route</span> again.</h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-paper-200/80">Find real routes, useful journey details, and expected fares before you leave home.</p>
        <div className="mt-9 flex justify-center"><Link to="/routes" className="rounded-lg bg-marigold-500 px-6 py-3 font-semibold text-ink-950 transition hover:bg-marigold-400">Find a route</Link></div>
      </div>
    </header>
    <section className="bg-gradient-to-b from-micro-50 to-paper py-16 sm:py-20"><div className="mx-auto grid max-w-6xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-12"><div className="text-center lg:col-span-5 lg:text-left"><p className="mb-3 text-sm font-bold uppercase tracking-wider text-micro-700">Plan your journey</p><h2 className="font-display text-3xl font-semibold sm:text-4xl">Try it right now</h2><p className="mt-4 leading-7 text-ink-500">Pick your starting point and destination. We’ll look for the best available journey in the live route data.</p></div><form onSubmit={handleSearch} className="ticket-stub mx-auto w-full max-w-lg space-y-4 bg-paper-100 p-6 shadow-card sm:p-8 lg:col-span-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-micro-50 text-micro-700"><FaSearch /></span><div><h3 className="font-display text-xl font-semibold">Find your route</h3><p className="text-sm text-ink-500">Search available vehicles</p></div></div><label className="block text-sm font-semibold text-ink-700">Current location<span className="relative mt-2 block"><FaMapMarkerAlt className="absolute left-4 top-1/2 -translate-y-1/2 text-micro-600" /><input value={from} onChange={(e) => setFrom(e.target.value)} required placeholder="Type a place, e.g. Thimi" className="w-full rounded-lg border border-ink-100 bg-paper px-4 py-3 pl-11 text-ink-900 outline-none transition focus:border-micro-600 focus:ring-2 focus:ring-micro-100" /></span></label><label className="block text-sm font-semibold text-ink-700">Destination<span className="relative mt-2 block"><FaMapMarkerAlt className="absolute left-4 top-1/2 -translate-y-1/2 text-brick-600" /><input value={to} onChange={(e) => setTo(e.target.value)} required placeholder="Type a place, e.g. Baneshwor" className="w-full rounded-lg border border-ink-100 bg-paper px-4 py-3 pl-11 text-ink-900 outline-none transition focus:border-micro-600 focus:ring-2 focus:ring-micro-100" /></span></label><button className="w-full rounded-lg bg-micro-600 py-3 font-semibold text-white transition hover:bg-micro-700">Search available vehicles</button></form></div></section>
    <section className="border-y border-ink-100 bg-paper-100 py-20"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto mb-12 max-w-2xl text-center"><h2 className="font-display text-3xl font-semibold sm:text-4xl">Designed for daily utility</h2><p className="mt-4 text-ink-500">Straightforward commuter information when you need it.</p></div><div className="grid gap-6 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-ink-100 bg-paper p-6 transition hover:-translate-y-1 hover:border-micro-600/30 hover:shadow-card"><span className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-micro-50 text-xl text-micro-700"><Icon /></span><h3 className="font-display text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-ink-500">{text}</p></article>)}</div></div></section>
    <section className="bg-paper py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="text-center"><h2 className="font-display text-3xl font-semibold sm:text-4xl">Kilometre-based fare guide</h2><p className="mx-auto mt-4 max-w-2xl text-ink-500">Use this simple distance guide to estimate your public-transport fare before you board.</p></div><div className="mt-10 overflow-hidden rounded-2xl border border-ink-100 bg-paper-100 shadow-card"><table className="w-full text-left text-sm"><thead className="bg-ink-900 text-paper-100"><tr><th className="px-5 py-4 font-semibold">Distance travelled</th><th className="px-5 py-4 text-right font-semibold">Regular fare</th><th className="px-5 py-4 text-right font-semibold">Student fare</th></tr></thead><tbody className="divide-y divide-ink-100"><tr><td className="px-5 py-4 font-medium">Up to 5 km</td><td className="px-5 py-4 text-right">Rs. 24</td><td className="px-5 py-4 text-right font-semibold text-marigold-700">Rs. 13</td></tr><tr><td className="px-5 py-4 font-medium">Up to 10 km</td><td className="px-5 py-4 text-right">Rs. 33</td><td className="px-5 py-4 text-right font-semibold text-marigold-700">Rs. 18</td></tr><tr><td className="px-5 py-4 font-medium">Up to 15 km</td><td className="px-5 py-4 text-right">Rs. 39</td><td className="px-5 py-4 text-right font-semibold text-marigold-700">Rs. 21</td></tr><tr><td className="px-5 py-4 font-medium">Up to 20 km</td><td className="px-5 py-4 text-right">Rs. 44</td><td className="px-5 py-4 text-right font-semibold text-marigold-700">Rs. 24</td></tr><tr><td className="px-5 py-4 font-medium">Above 20 km</td><td className="px-5 py-4 text-right">Rs. 50</td><td className="px-5 py-4 text-right font-semibold text-marigold-700">Rs. 28</td></tr></tbody></table></div><p className="mt-4 text-center text-xs text-ink-500">Student fares require a valid ID. Actual fares may vary by operator and route.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-ink-100 bg-paper-100 p-5 text-center"><FaClock className="mx-auto text-marigold-500" /><p className="mt-3 font-semibold">Plan ahead</p></div><div className="rounded-2xl border border-ink-100 bg-paper-100 p-5 text-center"><FaBus className="mx-auto text-micro-600" /><p className="mt-3 font-semibold">Choose your ride</p></div><div className="rounded-2xl bg-ink-900 p-5 text-center text-paper-100"><FaMoneyBillWave className="mx-auto text-marigold-400" /><p className="mt-3 font-semibold">Carry exact change when possible</p></div></div></div></section>
    <FAQ />
  </div>;
}
export default Home;
